name: Build, Set Version and Publish

on:
  push:
    branches:
      - 'release/v*' # Sadece release/v... branch'larında çalışır

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'

    - name: Extract version (remove "v")
      id: extract_version
      run: |
        echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        RAW_VERSION=${GITHUB_REF#refs/heads/release/}
        VERSION=${RAW_VERSION#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version extracted without v: $VERSION"

    - name: Check and update package.json version
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        echo "Target version: $VERSION"
        if [ "$CURRENT_VERSION" != "$VERSION" ]; then
          echo "Updating version..."
          npm version --no-git-tag-version $VERSION
        else
          echo "Version already correct, no update needed."
        fi
        cat package.json

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: |
        mkdir -p dist
        cp -r src bin package.json README.md dist

    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd dist
        npm publish

    - name: Push updated package.json
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "ci: update version to $VERSION [skip ci]" || echo "No changes to commit"
        git push origin HEAD

    - name: Generate release notes from commit messages
      id: release_notes
      run: |
        RELEASE_NOTES=$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD)
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
        echo "$RELEASE_NOTES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        name: Release v${{ env.VERSION }}
        body: ${{ env.RELEASE_NOTES }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request to master
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "ci: merge release v${{ env.VERSION }} to master"
        title: "Release v${{ env.VERSION }}"
        body: "Automated pull request to merge release branch to master"
        base: master
        branch: ${{ env.BRANCH_NAME }}